brew "coreutils"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask-drivers"
tap "netlify/netlifyctl"
tap "remind101/formulae"
tap "schniz/tap"
brew "act"
brew "asciinema"
brew "awscli"
brew "bat"
brew "circleci"
brew "diff-so-fancy"
brew "elixir"
brew "erlang"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "git-revise"
brew "git-trim"
brew "github/gh/gh"
brew "go"
brew "hub"
brew "httpie"
brew "jq"
brew "less"
brew "mas"
brew "netlifyctl"
brew "neovim"
brew "now-cli"
brew "openssl"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rustup"
brew "ruby", link: true
brew "fnm"
brew "scapple"
brew "starship"
brew "terraform"
brew "tig"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "vim"
brew "watchman"
brew "wget"
brew "zplug"
brew "zsh"
brew "remind101/formulae/assume-role"
cask "1password"
cask "alfred"
cask "bose-updater"
cask "discord"
cask "docker"
cask "firefox-developer-edition"
cask "font-fontawesome"
cask "font-inter"
cask "font-sanfrancisco"
cask "font-sauce-code-pro-nerd-font"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "kap"
cask "loom"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
mas "Contrast", id: 1254981365
mas "Focus Matrix", id: 1087284172
mas "Be Focused Pro", id: 961632517
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
