tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "netlify/netlifyctl"
tap "remind101/formulae"
tap "universal-ctags/universal-ctags"
cask "java8"
brew "asciinema"
brew "awscli"
brew "diff-so-fancy"
brew "elixir"
brew "erlang"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "go"
brew "httpie"
brew "less"
brew "mas"
brew "mongodb"
brew "netlifyctl"
brew "neovim"
brew "openssl"
brew "python"
brew "ripgrep"
brew "ruby", link: true
brew "terraform"
brew "tig"
brew "tmux"
brew "universal-ctags", args: ["HEAD"]
brew "vim"
brew "watchman"
brew "yarn", args: ["ignore-dependencies"]
brew "zplug"
brew "zsh"
brew "remind101/formulae/assume-role"
cask "1password"
cask "discord"
cask "docker"
cask "github"
cask "google-back-and-sync"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "keybase"
cask "marshallofsound-google-play-music-player"
cask "paw"
cask "postman"
cask "slack"
cask "spark"
cask "steam"
cask "visual-studio-code"
cask "vlc"
mas "Contract", id: 1254981365
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
